// flow-typed signature: 35048dc80b586f21d9c510b76cd1f758
// flow-typed version: <<STUB>>/gulp-babel_v^7.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-babel/index' {
  declare module.exports: $Exports<'gulp-babel'>;
}
declare module 'gulp-babel/index.js' {
  declare module.exports: $Exports<'gulp-babel'>;
}
